"""
Django settings for arc_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-hj+2+o*ywt0200s9a+ze4u#x79_j2t-s&@fzpx7-zn_cr!=)r*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    "regulatory_rules",
    'community.apps.CommunityConfig',
    'sites.apps.SitesConfig',
    'complaince',
    'test_check',
    'django_celery_beat',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arc_backend.urls'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arc_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER', default='Arc_New'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv()) if not CORS_ALLOW_ALL_ORIGINS else []

# CSRF settings for ngrok and production
def format_csrf_origins(origins):
    """Ensure CSRF origins have proper scheme"""
    formatted = []
    for origin in origins:
        origin = origin.strip()
        if origin and not origin.startswith(('http://', 'https://')):
            # Default to https for production-like domains, http for local IPs
            if any(local in origin for local in ['127.0.0.1', 'localhost', '192.168.', '10.']):
                origin = f'http://{origin}'
            else:
                origin = f'https://{origin}'
        formatted.append(origin)
    return formatted

csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='https://arcgis-frontend.vercel.app/', cast=Csv())
CSRF_TRUSTED_ORIGINS = format_csrf_origins(csrf_origins)

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Logging: Serverless platforms like Vercel mount the deployment under a read-only tree (/var/task).
# A FileHandler writing to BASE_DIR/celery_logs.log fails at import with OSError 30 (read-only fs).
CELERY_LOG_FILE = BASE_DIR / 'celery_logs.log'
_is_serverless = (
    bool(os.environ.get('VERCEL')) or
    bool(os.environ.get('VERCEL_ENV')) or
    bool(os.environ.get('AWS_LAMBDA_FUNCTION_NAME')) or
    str(BASE_DIR).startswith('/var/task')  # Vercel specific
)
_file_logging_opt_in = config('DJANGO_FILE_LOGGING', default=False, cast=bool)
_use_file_log = (not _is_serverless) and _file_logging_opt_in  # Only enable if explicitly opted in AND not serverless
_log_file_path = (Path('/tmp') / 'celery_logs.log') if _is_serverless else CELERY_LOG_FILE

_handlers = {
    'console': {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}
_task_handlers = ['console']
if _use_file_log:
    _handlers['celery_file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': str(_log_file_path),
        'formatter': 'verbose',
    }
    _task_handlers = ['console', 'celery_file']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': _handlers,
    'loggers': {
        'complaince.tasks': {
            'handlers': list(_task_handlers),
            'level': 'INFO',
            'propagate': False,
        },
        'complaince.signals': {
            'handlers': list(_task_handlers),
            'level': 'INFO',
            'propagate': False,
        },
        'regulatory_rules.tasks': {
            'handlers': list(_task_handlers),
            'level': 'INFO',
            'propagate': False,
        },
    },
}
